# Generated by Django 6.0 on 2025-12-24 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام دسته\u200cبندی"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="آدرس سئو (Slug)"
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام شرکت/بیمارستان"),
                ),
                ("logo", models.ImageField(upload_to="clients/", verbose_name="لوگو")),
                (
                    "show_on_home",
                    models.BooleanField(
                        default=True, verbose_name="نمایش در صفحه اصلی"
                    ),
                ),
            ],
            options={
                "verbose_name": "مشتری/پروژه",
                "verbose_name_plural": "مشتریان",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان خدمت")),
                ("description", models.TextField(verbose_name="توضیحات کامل خدمت")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="تصویر مرتبط",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نمایش در سایت"),
                ),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمات ما",
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("repair", "درخواست تعمیرکار (حضوری)"),
                            ("support_call", "پشتیبانی و مشاوره تلفنی"),
                            ("purchase", "مشاوره خرید"),
                            ("installation", "نصب و راه\u200cاندازی"),
                        ],
                        default="repair",
                        max_length=20,
                        verbose_name="نوع درخواست",
                    ),
                ),
                (
                    "machine_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مدل دستگاه (اختیاری)"
                    ),
                ),
                ("description", models.TextField(verbose_name="شرح مشکل یا درخواست")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید - بررسی نشده"),
                            ("pending", "در حال هماهنگی"),
                            ("done", "انجام شد"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست مشتری",
                "verbose_name_plural": "درخواست\u200cهای مشتریان",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام محصول")),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("screw", "اسکرو (Screw)"),
                            ("piston", "پیستونی (Piston)"),
                            ("portable", "معدنی/پرتابل"),
                            ("dryer", "درایر/خشک\u200cکن"),
                            ("filter", "فیلتر و قطعات مصرفی"),
                            ("generator", "ژنراتور اکسیژن/نیتروژن"),
                            ("other", "سایر تجهیزات"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="نوع دستگاه",
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات فنی")),
                (
                    "capacity",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ظرفیت/توان (اختیاری)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/", verbose_name="تصویر محصول"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="موجود/نمایش داده شود"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
    ]
