# Generated by Django 6.0 on 2026-01-02 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, verbose_name="عنوان مشخصه (مثلا: فشار کاری)"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=255, verbose_name="مقدار (مثلا: ۱۰ بار)"
                    ),
                ),
            ],
            options={
                "verbose_name": "مشخصه فنی",
                "verbose_name_plural": "مشخصات فنی",
            },
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.AlterModelOptions(
            name="servicerequest",
            options={
                "verbose_name": "درخواست خدمت",
                "verbose_name_plural": "درخواست\u200cهای خدمات",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="servicerequest",
            name="description",
        ),
        migrations.RemoveField(
            model_name="servicerequest",
            name="machine_model",
        ),
        migrations.RemoveField(
            model_name="servicerequest",
            name="request_type",
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="نام شرکت/جایگاه"
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="message",
            field=models.TextField(default="-", verbose_name="متن درخواست"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("repair", "تعمیرات اساسی"),
                    ("overhaul", "اورهال (Overhaul)"),
                    ("piping", "پایپینگ و لوله\u200cکشی"),
                    ("emergency", "اعزام فوری کارشناس"),
                    ("support", "پشتیبانی تلفنی"),
                ],
                default="-",
                max_length=20,
                verbose_name="نوع خدمت",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نمایش در سایت"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="شماره تماس"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[("new", "بررسی نشده"), ("done", "انجام شده")],
                default="new",
                max_length=10,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AddField(
            model_name="technicalspecification",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specs",
                to="catalog.product",
                verbose_name="محصول",
            ),
        ),
    ]
