# Generated by Django 6.0 on 2026-01-03 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_technicalspecification_delete_service_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان خدمت")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="آدرس سئو"
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="مثلا: fas fa-tools",
                        max_length=50,
                        verbose_name="کلاس آیکون",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(verbose_name="توضیح کوتاه صفحه اصلی"),
                ),
                (
                    "full_description",
                    models.TextField(verbose_name="توضیح کامل صفحه اختصاصی"),
                ),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمات",
            },
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.AlterModelOptions(
            name="servicerequest",
            options={
                "verbose_name": "درخواست مشتری",
                "verbose_name_plural": "درخواست\u200cهای خدمات",
            },
        ),
        migrations.AlterModelOptions(
            name="technicalspecification",
            options={},
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="model_type",
        ),
        migrations.RemoveField(
            model_name="servicerequest",
            name="status",
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, unique=True, verbose_name="آدرس سئو"
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="شرکت"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="message",
            field=models.TextField(default="-", verbose_name="متن درخواست"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="تماس"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="service_type",
            field=models.CharField(max_length=50, verbose_name="نوع خدمت"),
        ),
        migrations.AlterField(
            model_name="technicalspecification",
            name="key",
            field=models.CharField(max_length=100, verbose_name="ویژگی"),
        ),
        migrations.AlterField(
            model_name="technicalspecification",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specs",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="technicalspecification",
            name="value",
            field=models.CharField(max_length=255, verbose_name="مقدار"),
        ),
    ]
