# Generated by Django 6.0 on 2026-01-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_service_delete_client_alter_servicerequest_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicerequest",
            options={
                "verbose_name": "درخواست خدمت",
                "verbose_name_plural": "درخواست\u200cهای خدمت",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("compressor", "کمپرسور"),
                    ("oxygen_generator", "ژنراتور اکسیژن"),
                    ("spare_parts", "قطعات یدکی"),
                    ("oil", "روغن صنعتی"),
                    ("cng", "تجهیزات CNG"),
                    ("other", "سایر"),
                ],
                default="other",
                max_length=50,
                verbose_name="نوع محصول",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon_class",
            field=models.CharField(
                choices=[
                    ("fas fa-tools", "آچار و ابزار (تعمیرات)"),
                    ("fas fa-cogs", "چرخ\u200cدنده (اورهال)"),
                    ("fas fa-project-diagram", "دیاگرام (پایپینگ)"),
                    ("fas fa-headset", "هدفون (پشتیبانی)"),
                    ("fas fa-gas-pump", "پمپ (جایگاه CNG)"),
                    ("fas fa-check-shield", "سپر (ایمنی و بازرسی)"),
                    ("fas fa-truck", "کامیون (حمل و نقل)"),
                    ("fas fa-industry", "کارخانه (نصب و راه\u200cاندازی)"),
                    ("fas fa-oil-can", "روغن\u200cدان (سرویس دوره\u200cای)"),
                ],
                default="fas fa-tools",
                max_length=50,
                verbose_name="انتخاب آیکون",
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="company_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="نام شرکت"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="message",
            field=models.TextField(blank=True, verbose_name="توضیحات تکمیلی"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="شماره تماس"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="service_type",
            field=models.CharField(max_length=150, verbose_name="نوع خدمت"),
        ),
    ]
